# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa335f2b17a039018eb32d17c89ede4dc09086c7257e149472e5a6e25303faf8c42d91b7add0f5e5732270ecaa196edc8e4ace51c25bdb40f00074d4235966fa

test:
  secret_key_base: b2cb0102f8d41892f3f166c51f57aed694d96cebd26b24ceb4a53defaf2911e0ad96759a5fe418f11b46cd3bc3496774a9e4a8b65047be97e90454d449eaa4b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
